# -*- coding: utf-8 -*-
"""LLNchatbotforpAIker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfdRMPCLEur_TMTK0W6XWms_dPTjS_MD

## Building a Multilingual AI

To create an AI that detects the input language and responds in that same language, you'll generally need the following:

1.  **Language Detection**: Identify the language of the user's input.
2.  **Natural Language Understanding (NLU)**: Process and understand the user's intent and content.
3.  **Response Generation**: Create a relevant response. This often involves a Large Language Model (LLM).
4.  **Language Generation/Translation (if necessary)**: If your core model generates responses in one language, you might need to translate it back to the detected input language. However, many modern LLMs can directly generate responses in various languages.

Let's start with **Language Detection**. A popular and effective library for this is `langdetect`.
"""

# Install the langdetect library, which is used for detecting the language of text.
!pip install langdetect

from langdetect import detect # Import the detect function from the langdetect library

# This function detects language of a given text input
def detect_language(t): # Define a function named detect_language that takes 't' (text) as input
    print("Attempting to detect language...") # Print a debug message to show function is running
    try:
     return detect(t) # Try to detect the language of the input text 't'
    except:
     return "Could not detect language: An unknown error occurred" # If detection fails, return an error message

# Test the language detection function with different language texts
s_txt = "Hola, ¿cómo estás?" # Spanish text example
e_txt = "Hello, how are you?" # English text example
f_txt = "Bonjour, comment ça va ?" # French text example

# Print the detected language for each example text
print(f"'{s_txt}' is in: {detect_language(s_txt)}")
print(f"'{e_txt}' is in: {detect_language(e_txt)}")
print(f"'{f_txt}' is in: {detect_language(f_txt)}")

"""Next, let's look at **Response Generation** using a Large Language Model (LLM). We'll use the Gemini API for this. First, you'll need to set up your API key.

### Gemini API Setup

To use the Gemini API, you'll need an API key. If you don't already have one, create a key in [Google AI Studio](https://makersuite.google.com/).

In Colab, add the key to the secrets manager under the "🔑" icon in the left panel. Give it the name `GOOGLE_API_KEY`. Then pass the key to the SDK:
"""

# Install the Google Generative AI Python SDK, which allows us to interact with Gemini models
!pip install -q -U google-generativeai

import google.generativeai as genai # Import the generative AI library
from google.colab import userdata # Import userdata to securely access API keys


# API key setup, very important for authenticating with the Gemini API
GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY') # Retrieve the API key from Colab secrets
genai.configure(api_key=GOOGLE_API_KEY) # Configure the genai library with the API key

# Initialize the Generative Model, specifying 'gemini-flash-latest' to use the most recent Flash model
gemini_model = genai.GenerativeModel('gemini-flash-latest') # Switched to gemini-flash-latest to avoid availability issues

# Loop through all available generative models to check which ones support content generation
for m in genai.list_models(): # Get a list of all models
  if 'generateContent' in m.supported_generation_methods: # Check if the model supports generating content
    print(m.name) # Print the name of the models that support content generation

"""Now, let's combine language detection with a simple prompt to the Gemini model to make it respond in the detected language."""

# Define a function to get a multilingual AI response
def multilingual_ai_response(u_in): # Takes user input 'u_in' as an argument
    d_lng = detect_language(u_in) # Detect the language of the user input
    if "Could not detect language" in d_lng: # Check if language detection failed
        print("Language detection failed!") # Oh no! Print an error message
        return f"Sorry, I couldn't understand the language of your input. Please try again. ({d_lng})" # Return an error response

    # Craft a prompt that encourages the model to respond in the detected language
    # This ensures the AI's response is in the same language as the user's query
    p_str = "You are an AI assistant. The user's input is in " + d_lng + ". Please respond to the following query in " + d_lng + ":\n\nUser: " + u_in + "\nAI:" # Construct the prompt string

    try:
        response = gemini_model.generate_content(p_str) # Send the prompt to the Gemini model to generate a response
        return response.text # Return the AI's generated text response
    except:
        return "An error occurred while generating a response, check your internet or API key!" # Handle any errors during response generation

# Test the multilingual AI response function with inputs in different languages
print("--- English Input ---") # Section header for English test
eng_q = "What is the capital of France?" # English query
print(f"Input: {eng_q}") # Print the input query
print(f"Response: {multilingual_ai_response(eng_q)}\n") # Print the AI's response

print("--- Spanish Input ---") # Section header for Spanish test
spa_q = "¿Cuál es la capital de España?" # Spanish query
print(f"Input: {spa_q}") # Print the input query
print(f"Response: {multilingual_ai_response(spa_q)}\n") # Print the AI's response


print("--- French Input ---") # Section header for French test
fre_q = "Comment dit-on 'hello' en allemand ?" # French query
print(f"Input: {fre_q}") # Print the input query
print(f"Response: {multilingual_ai_response(fre_q)}\n") # Print the AI's response

"""### Start a Conversation"""

# Start an interactive chat session with the AI bot
print("Start chatting with the bot! Type 'exit' or 'quit' to end the conversation.")
while True: # Start an infinite loop for continuous conversation
    u_in = input("You: ") # Get user input
    print("Processing your input...") # Added for fun, indicates the bot is thinking
    if u_in.lower() in ['exit', 'quit']: # Check if the user wants to end the conversation
        print("Bot: Goodbye!") # Bot says goodbye
        break # Exit the loop, ending the conversation

    b_resp = multilingual_ai_response(u_in) # Get a multilingual response from the AI for the user's input
    print(f"Bot: {b_resp}") # Print the AI's response

"""This provides a basic framework. For a more robust system, you might consider:

*   **Error Handling**: More sophisticated error handling for `langdetect` and `gemini_model`.
*   **Context Management**: For conversational AI, you'd need to maintain conversation history.
*   **Fine-tuning/Prompt Engineering**: Further refine prompts to ensure consistent language responses.
*   **Model Selection**: Experiment with different Gemini models or other LLMs that excel at multilingual tasks.
"""